In [1]:
import numpy as np

def matrix_multiply(A, B):
    # Get the dimensions of the matrices
    m, n = A.shape
    p, q = B.shape
    
    # Check if the matrices can be multiplied
    if n != p:
        print("Matrices cannot be multiplied. Inner dimensions do not match.")
        return None
    
    # Initialize the result matrix
    C = np.zeros((m, q))
    
    # Perform matrix multiplication
    for i in range(m):
        for j in range(q):
            for k in range(n):
                C[i, j] += A[i, k] * B[k, j]
    
    return C

# Example usage
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

result = matrix_multiply(A, B)
print("Result of matrix multiplication:")
print(result)


Result of matrix multiplication:
[[19. 22.]
 [43. 50.]]


In [2]:
import numpy as np

# Example matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Matrix multiplication using NumPy
result = np.dot(A, B)
# Alternatively, you can use the @ operator for matrix multiplication in Python 3.5+
# result = A @ B

print("Result of matrix multiplication:")
print(result)


Result of matrix multiplication:
[[19 22]
 [43 50]]


In [2]:
import numpy as np

# Example matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Matrix multiplication using np.matmul()
result = np.matmul(A, B)

print("Result of matrix multiplication:")
print(result)


Result of matrix multiplication:
[[19 22]
 [43 50]]


In [3]:
A = np.array([[3, -1, 1, 2],
              [6, -4, 3, 5],
              [3, -13, 9, 3],
              [-6, 4, 1, -18]])

I = np.array([[1, 1, 1, 1],
              [1, 1, 1, 1],
              [1, 1, 1, 1],
              [1, 1, 1, 1]])

In [5]:
result = np.matmul(I, A)
result

array([[  6, -14,  14,  -8],
       [  6, -14,  14,  -8],
       [  6, -14,  14,  -8],
       [  6, -14,  14,  -8]])